import type { Metadata } from "next";

import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { SectionFooter } from "@/components/SectionFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>
        {children}
        <SectionFooter></SectionFooter>
      </body>
    </html>
  );
}
